import { NextRequest } from "next/server";
import { describe, expect, it } from "vitest";
import { POST as transcribeRoute } from "@/app/api/transcribe/route";
import {
  formatTime,
  formatSrtTime,
  formatVttTime,
  exportToSrt,
  exportToVtt,
  exportToTxt,
  exportToJson,
  exportToCsv,
  exportToPdfHtml,
  exportToDocx,
  SUPPORTED_LANGUAGES,
  type TranscriptSegment,
  type TranscriptionResult,
} from "@/src/lib/transcribe";

let ipCounter = 200;

function postJsonRequest(path: string, body: unknown): NextRequest {
  ipCounter += 1;
  return new NextRequest(`http://localhost:3000${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-forwarded-for": `203.0.115.${ipCounter % 250}`,
    },
    body: JSON.stringify(body),
  });
}

describe("Transcription Utility Functions & Multi-format Export", () => {
  const sampleSegments: TranscriptSegment[] = [
    {
      id: "seg-1",
      start: 0,
      end: 4.5,
      startFormatted: "00:00",
      endFormatted: "00:04",
      speaker: "Speaker 1",
      text: "Hello and welcome to MediaDocks video transcription.",
    },
    {
      id: "seg-2",
      start: 5.0,
      end: 11.2,
      startFormatted: "00:05",
      endFormatted: "00:11",
      speaker: "Speaker 2",
      text: "This is an accurate AI speech to text converter.",
    },
  ];

  const mockResult: TranscriptionResult = {
    id: "tr-test-1",
    title: "Test Presentation Video",
    duration: 11.2,
    durationFormatted: "00:11",
    language: "en",
    languageName: "English",
    mode: "ai",
    wordCount: 16,
    confidence: 0.98,
    mediaType: "video",
    segments: sampleSegments,
  };

  it("formats standard time correctly", () => {
    expect(formatTime(0)).toBe("00:00");
    expect(formatTime(65)).toBe("01:05");
    expect(formatTime(3665)).toBe("1:01:05");
  });

  it("formats SRT and VTT timestamps with millisecond precision", () => {
    expect(formatSrtTime(0)).toBe("00:00:00,000");
    expect(formatSrtTime(4.5)).toBe("00:00:04,500");
    expect(formatVttTime(4.5)).toBe("00:00:04.500");
  });

  it("exports subtitles to SRT standard format", () => {
    const srt = exportToSrt(sampleSegments);
    expect(srt).toContain("1\n00:00:00,000 --> 00:00:04,500\nSpeaker 1: Hello and welcome to MediaDocks video transcription.");
    expect(srt).toContain("2\n00:00:05,000 --> 00:00:11,200\nSpeaker 2: This is an accurate AI speech to text converter.");
  });

  it("exports subtitles to WebVTT format", () => {
    const vtt = exportToVtt(sampleSegments);
    expect(vtt).toContain("WEBVTT - Generated by MediaDocks");
    expect(vtt).toContain("00:00:00.000 --> 00:00:04.500");
    expect(vtt).toContain("<v Speaker 1>Hello and welcome to MediaDocks video transcription.");
  });

  it("exports plain text with timestamps and speaker tags", () => {
    const txt = exportToTxt(sampleSegments, { includeTimestamps: true, includeSpeakers: true });
    expect(txt).toContain("[00:00 - 00:04] Speaker 1: Hello and welcome to MediaDocks video transcription.");
    expect(txt).toContain("[00:05 - 00:11] Speaker 2: This is an accurate AI speech to text converter.");
  });

  it("exports full structured JSON", () => {
    const jsonStr = exportToJson(mockResult);
    const parsed = JSON.parse(jsonStr);
    expect(parsed.title).toBe("Test Presentation Video");
    expect(parsed.segments).toHaveLength(2);
  });

  it("exports to Excel / CSV format with metadata headers", () => {
    const csv = exportToCsv(sampleSegments, mockResult);
    expect(csv).toContain("# Title: Test Presentation Video");
    expect(csv).toContain("Segment,Start,End,Speaker,Text,Words");
    expect(csv).toContain('1,00:00,00:04,"Speaker 1","Hello and welcome to MediaDocks video transcription.",7');
  });

  it("exports to formatted print-ready PDF HTML", () => {
    const html = exportToPdfHtml(sampleSegments, mockResult);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("Test Presentation Video — Transcript");
    expect(html).toContain("Speaker 1");
    expect(html).toContain("00:00 – 00:04");
    expect(html).toContain("window.print()");
  });

  it("exports to valid DOCX binary blob", async () => {
    const docxBlob = await exportToDocx(sampleSegments, mockResult);
    expect(docxBlob).toBeInstanceOf(Blob);
    expect(docxBlob.size).toBeGreaterThan(500);
    expect(docxBlob.type).toBe("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  });

  it("defines comprehensive language options", () => {
    expect(SUPPORTED_LANGUAGES.length).toBeGreaterThan(30);
    const hasEnglish = SUPPORTED_LANGUAGES.some((l) => l.code === "en");
    const hasSpanish = SUPPORTED_LANGUAGES.some((l) => l.code === "es");
    const hasHindi = SUPPORTED_LANGUAGES.some((l) => l.code === "hi");
    expect(hasEnglish).toBe(true);
    expect(hasSpanish).toBe(true);
    expect(hasHindi).toBe(true);
  });
});

describe("POST /api/transcribe Endpoint", () => {
  it("returns 503 when GEMINI_API_KEY is not configured", async () => {
    const originalKey = process.env.GEMINI_API_KEY;
    delete process.env.GEMINI_API_KEY;

    try {
      const res = await transcribeRoute(postJsonRequest("/api/transcribe", {}));
      expect(res.status).toBe(503);
      const body = await res.json();
      expect(body.code).toBe("TRANSCRIPTION_UNAVAILABLE");
    } finally {
      if (originalKey) process.env.GEMINI_API_KEY = originalKey;
    }
  });

  // First case in this file to reach engine-tool discovery, which walks install
  // directories and spawns `-version` probes. That does not reliably fit in the
  // default 5s budget when the suite runs in parallel, hence the explicit one.
  it(
    "rejects an empty URL payload with 400 when configured",
    async () => {
      const originalKey = process.env.GEMINI_API_KEY;
      process.env.GEMINI_API_KEY = "test-gemini-key";

      try {
        const res = await transcribeRoute(postJsonRequest("/api/transcribe", {}));
        expect(res.status).toBe(400);
        const body = await res.json();
        expect(body.code).toBe("INVALID_URL");
      } finally {
        if (originalKey) {
          process.env.GEMINI_API_KEY = originalKey;
        } else {
          delete process.env.GEMINI_API_KEY;
        }
      }
    },
    30_000,
  );

  it("rejects invalid URL strings with 400", async () => {
    const originalKey = process.env.GEMINI_API_KEY;
    process.env.GEMINI_API_KEY = "test-gemini-key";

    try {
      const res = await transcribeRoute(
        postJsonRequest("/api/transcribe", { url: "not-a-valid-url" })
      );
      expect(res.status).toBe(400);
      const body = await res.json();
      expect(body.code).toBe("INVALID_URL");
    } finally {
      if (originalKey) {
        process.env.GEMINI_API_KEY = originalKey;
      } else {
        delete process.env.GEMINI_API_KEY;
      }
    }
  });
});
